import Foundation

/// Hand-drawn pixel art, stored as text grids. One character is one pixel.
/// Colors are picked in `AvatarView` and `BadgeIcon`, always from `Theme`.
///
/// Avatar keys:  `h` hair, `s` skin, `d` skin shade, `e` eyes, `t` shirt, `.` empty (backdrop shows).
/// Badge keys:   `#` ink, `w` white, `g` green accent, `.` empty.
enum PixelArt {

    /// Six people with different hairstyles: short crop, afro, braids, bun, cap, and curls.
    /// A student's avatar is picked from `Student.colorIndex`.
    static let avatars: [[String]] = [
        // crop
        [
            "............",
            "...hhhhhh...",
            "..hhhhhhhh..",
            "..hssssssh..",
            "..hsessesh..",
            "..hssssssh..",
            "..hssddssh..",
            "...ssssss...",
            "....dddd....",
            ".tttttttttt.",
            "tttttttttttt",
            "tttttttttttt",
        ],
        // afro
        [
            "..hhhhhhhh..",
            ".hhhhhhhhhh.",
            "hhhhhhhhhhhh",
            "hhhsssssshhh",
            "hhhsesseshhh",
            "hhhsssssshhh",
            "hhhssddsshhh",
            ".hh.ssss.hh.",
            "..h.dddd.h..",
            ".tttttttttt.",
            "tttttttttttt",
            "tttttttttttt",
        ],
        // braids
        [
            "...hhhhhh...",
            "..hhhhhhhh..",
            "..hhhhhhhh..",
            "..hssssssh..",
            "..hsessesh..",
            "..hssssssh..",
            "..hssddssh..",
            "..hhssssshh.",
            "..hh.dd.hh..",
            ".hhtttttthh.",
            "hhtttttttthh",
            "htttttttttth",
        ],
        // bun
        [
            "....hhhh....",
            "....hhhh....",
            "..hhhhhhhh..",
            "..hssssssh..",
            "..hsessesh..",
            "..hssssssh..",
            "..hssddssh..",
            "...ssssss...",
            "....dddd....",
            ".tttttttttt.",
            "tttttttttttt",
            "tttttttttttt",
        ],
        // cap
        [
            "............",
            "...tttttt...",
            "..tttttttt..",
            "..tttttttttt",
            "..hsessesh..",
            "..hssssssh..",
            "..hssddssh..",
            "...ssssss...",
            "....dddd....",
            ".tttttttttt.",
            "tttttttttttt",
            "tttttttttttt",
        ],
        // curls
        [
            "..h.hh.h.h..",
            "..hhhhhhhh..",
            "..hhhhhhhh..",
            "..hssssssh..",
            "..hsessesh..",
            "..hssssssh..",
            "..hssddssh..",
            "...ssssss...",
            "....dddd....",
            ".tttttttttt.",
            "tttttttttttt",
            "tttttttttttt",
        ],
    ]

    /// One 12 by 12 icon per badge, keyed by `Badge.id`.
    static let badges: [String: [String]] = [
        "first-steps": [
            "..##........",
            ".####.......",
            ".####.......",
            ".####.......",
            "..##...##...",
            "..##..####..",
            "......####..",
            "......####..",
            "......####..",
            ".......##...",
            ".......##...",
            "............",
        ],
        "explorer": [
            "...######...",
            "..#......#..",
            ".#...gg...#.",
            "#....gg....#",
            "#...gggg...#",
            "#...gggg...#",
            "#...####...#",
            "#...####...#",
            "#....##....#",
            ".#...##...#.",
            "..#......#..",
            "...######...",
        ],
        "regular": [
            ".#........#.",
            ".#........#.",
            "############",
            "############",
            "#..........#",
            "#.......g..#",
            "#......gg..#",
            "#.g...gg...#",
            "#.gg.gg....#",
            "#..gggg....#",
            "#...gg.....#",
            "############",
        ],
        "century": [
            "............",
            "############",
            "............",
            "..#.###.###.",
            ".##.#.#.#.#.",
            "..#.#.#.#.#.",
            "..#.#.#.#.#.",
            "..#.###.###.",
            "............",
            "............",
            "############",
            "............",
        ],
        "rising-star": [
            ".....##.....",
            ".....##.....",
            "....####....",
            "############",
            ".##########.",
            "..########..",
            "...######...",
            "..########..",
            "..###..###..",
            ".###....###.",
            ".##......##.",
            "............",
        ],
        "first-reward": [
            "...##..##...",
            "..#..gg..#..",
            "...##gg##...",
            "############",
            "#....gg....#",
            "############",
            ".#...gg...#.",
            ".#...gg...#.",
            ".#...gg...#.",
            ".#...gg...#.",
            ".#...gg...#.",
            ".##########.",
        ],
        "local-hero": [
            "............",
            ".##########.",
            "#g#g#g#g#g#g",
            "############",
            ".#........#.",
            ".#.######.#.",
            ".#.#....#.#.",
            ".#.#....#.#.",
            ".#.#..g.#.#.",
            ".#.#....#.#.",
            ".#.#....#.#.",
            "############",
        ],
        "all-in": [
            ".....#......",
            ".....##.....",
            "....###.#...",
            "...####.##..",
            "..#####.###.",
            "..###.#####.",
            ".####..#####",
            ".####.g.####",
            ".####ggg####",
            "..###ggg###.",
            "...#ggg###..",
            "....######..",
        ],
    ]
}
